In [2]:
import numpy

In [4]:
import pandas as pd

In [6]:
x=numpy.array([[1,2,3],[4,5,8],[1,7,9]])

In [8]:
print(x)

[[1 2 3]
 [4 5 8]
 [1 7 9]]


In [10]:
print(x.ndim)
print(x.shape)
print(x.size)

2
(3, 3)
9


In [12]:
import numpy as np

In [18]:
a=[1,2,3,4,5]

In [20]:
type(a)

list

In [22]:
import statistics
b=statistics.mean(a)
print(b)

3


In [24]:
c=statistics.median(a)
print(c)

3


In [26]:
d=[1,2,3,4,2,18]

In [28]:
type(d)

list

In [30]:
e=statistics.mode(d)
print(e)

2


In [34]:
f=np.array([1,2,3,4,5])

In [36]:
fn=f.sum()

In [38]:
print(fn)

15


In [40]:
cv=np.array(["Guava","Banana","Cherry","Apple"])
print(np.sort(cv))

['Apple' 'Banana' 'Cherry' 'Guava']
